### ISSUE TITLE
Wire protocol link is now dead

### ISSUE THREAD

**Issue by IcedQuinn** [cucumber/cucumber-lua#18]
The link to the wire protocol is now dead as upstream seems to have moved and killed that particular project.

**Comment by mpkorstanje** [comment]
Is this what you are looking for?

https://github.com/cucumber/cucumber-ruby-wire

**Comment by mpkorstanje** [comment]
That said, this project doesn't look alive much.

**Comment by mattwynne** [comment]
It's all still there. We just removed it from the core project so it's an optional plugin rather than shipped with Cucumber-Ruby by default. See [here](https://github.com/cucumber/cucumber-ruby/blob/8461102347cdb17f22c75b474f1dd6f3d5d89522/UPGRADING.md#with-cucumber-800) for help.

I'll update the docs for this project, they're way out of date.

**Comment by mattwynne** [comment]
Thanks for bringing this to our attention, @IcedQuinn! If you want any help getting up and running, you can find us to chat with in the https://cucumber.io/docs/community#slack

**Comment by mattwynne** [comment]
@IcedQuinn we haven't had anyone maintaining this library for some time. Would you be interested in helping us out with that?
